spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 2 # 커넥션풀 2개만 사용

  h2:
    console.enabled: true # http://localhost:8080/h2-console

  devtools:
    livereload:
      enabled: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
        jdbc:
          batch_size: 1000

logging.level:
  org.hibernate.SQL: debug

# 커넥션풀 디버깅을 위함
logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true